#!/bin/bash
set -euo pipefail
SERVER_ADDR=${SERVER_ADDR:-localhost:10666}
IWAD_PATH=${IWAD_PATH:-/var/wads/iwad.wad}
WAD_LIST=${WAD_LIST:-""}
INTERVAL_SECONDS=${INTERVAL_SECONDS:-10}
STARTUP_DELAY_SECONDS=${STARTUP_DELAY_SECONDS:-10}
SCREENSHOT_PNG_PATH=${SCREENSHOT_PNG_PATH:-/screenshot.png}
SCREENSHOT_JPG_PATH=${SCREENSHOT_JPG_PATH:-/screenshot.jpg}
SCREENSHOT_WORK_DIR=${SCREENSHOT_WORK_DIR:-/tmp/spectator-screenshots}
TICS_PER_SEC=35
interval_tics=$(( INTERVAL_SECONDS * TICS_PER_SEC ))
startup_tics=$(( STARTUP_DELAY_SECONDS * TICS_PER_SEC ))

RESOLVE_SCRIPT_PATH=$(dirname "$0")/resolve-by-id.sh
resolve_by_id() {
  "$RESOLVE_SCRIPT_PATH" $DATA_ROOT "$1"
}

cd ${DATA_ROOT:-/var/wads}

echo "Spectator is sleeping for $STARTUP_DELAY_SECONDS seconds before starting."
sleep "$STARTUP_DELAY_SECONDS"
while [[ ! -f "$IWAD_PATH" ]]; do
  echo "Waiting for IWAD at $IWAD_PATH ..."
  sleep 5
done
echo "Spectator starting, connecting to $SERVER_ADDR using IWAD $IWAD_PATH"

mkdir -p "$SCREENSHOT_WORK_DIR"

cat > /tmp/spectator.cfg <<EOF
// Autogenerated by /spectator.sh
set screenshot_type \"png\"
set screenshot_quiet 1
set screenshot_dir \"$SCREENSHOT_WORK_DIR\"

// Keep the HUD out of the way.
set screenblocks 12

// Take a shot (auto-named into screenshot_dir)
alias _spectator_shot \"spectate; spyrandom; wait 5; screenshot; wait 1\"

// Loop forever
alias _spectator_loop \"_spectator_shot; wait ${interval_tics}; _spectator_loop\"

// Give the client time to connect and receive initial state
wait ${startup_tics}
_spectator_loop
EOF

CLIENT=(
  /opt/zandronum/zandronum
  -iwad "$IWAD_PATH"
  -connect "$SERVER_ADDR"
  -width 640 -height 480
  -nosound -nomusic
  -exec /tmp/spectator.cfg
)
if [[ -n "${WAD_LIST:-}" ]]; then
  IFS=',' read -r -a WADS <<< "$WAD_LIST"
  for wad in "${WADS[@]}"; do
    wad="${wad#"${wad%%[![:space:]]*}"}"  # ltrim
    wad="${wad%"${wad##*[![:space:]]}"}"  # rtrim
    [[ -z "$wad" ]] && continue
    wad_path="$(resolve_by_id "$wad")"
    echo "Resolved PWAD id '$wad' to path '$wad_path'"
    if [[ ! -f "$wad_path" ]]; then
      echo "ERROR: PWAD not found after resolve: $wad_path"
      echo "Data root: $DATA_ROOT"
      ls -al $DATA_ROOT >&2 || true
      echo "WAD dir: $(dirname "$wad_path")"
      ls -al "$(dirname "$wad_path")" >&2 || true
      exit 1
    fi
    echo "Adding PWAD: $wad_path"
    CLIENT+=( -file "$wad_path" )
  done
fi

rm -f "$SCREENSHOT_PNG_PATH" "$SCREENSHOT_JPG_PATH" "$SCREENSHOT_JPG_PATH.tmp" 2>/dev/null || true

cd /opt/zandronum

# Run the client in a virtual X server.
# NOTE: Zandronum still needs an X display for rendering, even for screenshots.
echo ">>> ${CLIENT[*]}"
xvfb-run -a -s "-screen 0 640x480x24" "${CLIENT[@]}" &

game_pid=$!

term() {
  echo "Got SIGTERM, forwarding to client pid=$game_pid"
  kill -TERM "$game_pid" 2>/dev/null || true
}
trap term TERM INT

last_mtime=""
while kill -0 "$game_pid" 2>/dev/null; do
  newest_png=$(ls -1t "$SCREENSHOT_WORK_DIR"/*.png 2>/dev/null | head -n 1 || true)
  if [[ -n "${newest_png:-}" && -f "$newest_png" ]]; then
    mtime=$(stat -c %Y "$newest_png" 2>/dev/null || echo "")
    if [[ -n "$mtime" && "$mtime" != "$last_mtime" ]]; then
      last_mtime="$mtime"

      # Atomically publish the PNG (best-effort; may be unwritable under --user/--read-only).
      cp -f "$newest_png" "$SCREENSHOT_PNG_PATH.tmp" 2>/dev/null || true
      mv -f "$SCREENSHOT_PNG_PATH.tmp" "$SCREENSHOT_PNG_PATH" 2>/dev/null || true

      # Enforce exact 640x480 and atomically publish JPG (best-effort).
      if command -v convert >/dev/null 2>&1; then
        convert "$newest_png" -resize 640x480\! "$SCREENSHOT_JPG_PATH.tmp" 2>/dev/null || true
        mv -f "$SCREENSHOT_JPG_PATH.tmp" "$SCREENSHOT_JPG_PATH" 2>/dev/null || true
      fi
    fi
  fi
  sleep 1
done

wait "$game_pid"
